### ISSUE TITLE
Required changes to df_by_f

### ISSUE THREAD

**Issue by soumyaaymous** [dilawar/roi_locator#1]
- [x] baseline of each roi should be the avg value of the first 5 frames of that roi
- [x] Perform trial averaged traces (of all the videos in that directory)
- [x] Clean up y axis(currently its difficult to read)
- [x] X-axis: should ask for trial duration and number of frames and calculate frame rate. X axis should display time in milliseconds (500ms, 1000ms, 1500ms etc)
- [x] Scalebar on the side
1. Ask for CS- trials and plot it seperately (same as CS+, should plot trial averages). Should have a provision for 'No CS-'

On a Seperate Code:
Filter: Seperate code with filter
Shows spikes and lows (inhibition). Above +2 and Below -0.5 std dev respectively.

**Comment by soumyaaymous** [comment]
Please Ignore the point about the CS- for now

**Comment by dilawar** [comment]
![trial3-roi-1 tif_dfbyf dat_df_by_f](https://cloud.githubusercontent.com/assets/895681/12552481/0c735948-c398-11e5-9e8d-8d3b74af0623.png)

**Comment by soumyaaymous** [comment]
Dear Dilawar.
Thanks for implementing this baseline. Also, in the hot scale, does white
represent high activity? I think the reverse is better as the dark colour
would be easier to see.
Also, please see if you can implement the trace averaged  plotting. That is
at the heart of what i am trying to see.

Thanks and best regards

Soumya Bhattacharjee
PhD Scholar and Graduate Student
Bhalla Lab
The National Centre for Biological Sciences
UAS, GKVK
Bellary Road
Bangalore 560065
Karnataka

**Comment by dilawar** [comment]
I'll change the hotline. 
I am not sure how you'd like to have the trial average. You want one plot for
each video or all frames should be appended? Or for each roi, I take the average
of recordings (from the directory)?

## 

best,
    Dilawar

**Comment by soumyaaymous** [comment]
Dear dilawar,
I will come and discuss with in 45 mins. You can also look at the Matlab
coffee to see how Ashesh and mehrab did it. I will have to look it up,i am
not familiar with how they did the averaging.
Best regards
